### ISSUE TITLE
polyline with "no frame colour" is not visible even if alarm-colour is activated

### ISSUE THREAD

**Issue by triessner** [tnentwig/WebVisu#17]
In my visu I use a trick to hide a line sometimes. I checked the "no frame colour" checkbox and as a result in the codesys-visu it is hidden, when the alarm variable is false, and it is visible with the alarm-colour when the alarm variable is true.
In the javascript visu it is hidden all the time, no matter whether the alarm variable is false or true.
I know, that I can solve this issue with the hidden variable, but I just want to give a hint, that there is a difference between the java and the javascript version.

**Comment by Ekristoffe** [comment]
Could you test with this version:
https://github.com/Ekristoffe/WebVisu/tree/Dev/dist
It should be fixed.

**Comment by triessner** [comment]
In my visu it doesn't work. The line is still not visible in spite of setting the alarm variable of that line to true.

**Comment by Ekristoffe** [comment]
Strange, is it possible to know what parameter you are using on this line ?

**Comment by triessner** [comment]
I don't understand, what you mean. As I explained in my initial post to this issue, I'm using the alarm variable of the polyline, to set the normal colour (false) or the alarm colour (true). As I chcked the "no frame colour" checkbox, the line is normally invisible. But it is visible with the alarm colour (alarm variable set "true"). I don't use other parameters.

**Comment by Ekristoffe** [comment]
Same for me I have tested this parameter with variable, constants, constants + variable and it is working on my machine ...
I don’t understand what wrong with it ...
Is the variable Boolean or another type ?

**Comment by triessner** [comment]
It is boolean. Maybe it is more clear, if I put in here two screenshots. They are in german, but I hope they are helpful nevertheless.
This is the dialogue of the polyline (german "Linienzug") for the colours (german "Farben") with the checkbox "no frame colour" (german "Keine Rahmenfarbe) 
![Screenshot_20210112_192847](https://user-images.githubusercontent.com/3670326/104356874-c0f23780-550c-11eb-8061-c300f553ba1b.png)
This is the dialogue for the variables (german "Variablen") with the variable for the colour change (german "Farbwechsel")
![Screenshot_20210112_192936](https://user-images.githubusercontent.com/3670326/104356844-bafc5680-550c-11eb-858a-766246dbc705.png)

**Comment by Ekristoffe** [comment]
Found it! it should be fixed in the next release. Thanks

**Comment by triessner** [comment]
I'm not very familiar with github and javascript. Where can I get the new `webvisu.js`? Do I also have to upgrade the `webvisu.html` with every fix?

**Comment by triessner** [comment]
OK that works now
